language: haskell
ghc: 7.8

branches:
  only:
    - master
    - use-cabal-sandbox-on-travis

cache:
  directories:
    - .cabal-sandbox

before_install:
  - sudo apt-get install -y libblas-dev libatlas-dev liblapack-dev
  - ls -al .
  - ls -al .cabal-sandbox
  - test -d .cabal-sandbox/lib || cabal sandbox init
  - ls -al .
  - ls -al .cabal-sandbox


script:
  - cabal configure --enable-tests && cabal build && cabal test --show-details=always
  - ls -al .
  - ls -al .cabal-sandbox
