language: haskell
ghc: 7.8

branches:
  only:
    - master
    - use-cabal-sandbox-on-travis

cache:
  directories:
    - .cabal-sandbox

before_install:
  - sudo apt-get install -y libblas-dev libatlas-dev liblapack-dev
  - cabal sandbox init

script:
  - cabal configure --enable-tests && cabal build && cabal test --show-details=always
