language: haskell
ghc: 7.8

branches:
  only:
    - master

cache:
  directories:
    - my_cabal_sandbox

before_install:
  - sudo apt-get install -y libblas-dev libatlas-dev liblapack-dev
  - ls -la .
  - cabal sandbox init --sandbox my_cabal_sandbox

script:
  - cabal configure --enable-tests && cabal build && cabal test --show-details=always
