language: haskell
ghc: 7.8

branches:
  only:
    - master

cache:
  directories:
    - .cabal-sandbox
    - cabal.sandbox.config

before_install:
  - sudo apt-get install -y libblas-dev libatlas-dev liblapack-dev
  - ls -la .
  - ls -la .cabal-sandbox
  - rm -r .cabal-sandbox
  - test -d .cabal-sandbox || cabal sandbox init

script:
  - cabal configure --enable-tests && cabal build && cabal test --show-details=always
