language: haskell
ghc: 7.8
before_install:
  - sudo apt-get install -y libblas-dev libatlas-dev liblapack-dev
script:
  - cabal configure --enable-tests && cabal build && cabal test --show-details=always