language: haskell
ghc: 7.8

branches:
  only:
    - master
    - use-cabal-sandbox-on-travis

cache:
  directories:
    - my-cabal-sandbox

before_install:
  - sudo apt-get install -y libblas-dev libatlas-dev liblapack-dev
  - cp cabal.sandbox.config.travis cabal.sandbox.config
  - ls -al .
  - ls -al my-cabal-sandbox
  - test -d my-cabal-sandbox/packages || cabal sandbox init --sandbox my-cabal-sandbox
  - cat cabal.sandbox.config
  - ls -al .
  - ls -al my-cabal-sandbox

script:
  - cabal configure --enable-tests && cabal build && cabal test --show-details=always
  - ls -al .
  - ls -al my-cabal-sandbox
